# php service
# https://hub.docker.com/_/php
# Official Debian 9 - php 7.3
from php:7.3-fpm-buster

ARG DEBIAN_FRONTEND=noninteractive

# Update the sources list
RUN apt-get clean && apt-get update

# apt-utils fix
RUN apt-get install -y --no-install-recommends apt-utils

# Install basic applications
RUN apt-get install -y tar git curl nano wget dialog net-tools build-essential locales

# Install python3.
RUN apt-get install -y python3

ENV DEBIAN_FRONTEND teletype
ENV PYTHONIOENCODING UTF-8

# Pip
RUN apt-get install -y python3-pip

# Install python3 libraries.
RUN pip3 install PyMySQL requests PyYAML lxml aerofiles pathlib2 
RUN pip3 install geographiclib geopy simplejson geojson folium flask

# Write aliases for python exec
RUN echo 'alias python=python3' >> ~/.bashrc && \
    echo 'alias pip=pip3' >> ~/.bashrc

# MySQLi docker extension
RUN docker-php-ext-install mysqli

# Set the locale
RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen && \
    export LANGUAGE="en_GB.UTF-8" && \
    update-locale LANG=en_GB.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8


# Make Application User the same as Host user
# to avoid disk access problems
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN userdel -f www-data && \
    if getent group www-data ; then groupdel www-data; fi && \
    groupadd -g ${GROUP_ID} www-data && \
    useradd -l -u ${USER_ID} -g www-data www-data

